### ISSUE TITLE
Test: bootloader restore at testing start

### ISSUE THREAD

**Issue by cederom** [mbedmicro/DAPLink#305]
Interrupting test may lead to condition where bootloader is broken and further testing is not possible. Test framework can be updated to first upload initial bootloader and firmware at start in order to have known start condition..

```
Board: Name=FRDM-K64F Unique ID=0240000028884e45001070116bf000478021000097969900
Application: Name=k20dx_frdmk64f_if
Bootloader: Name=k20dx_bl
Target: Name=FRDM-K64F
SubTest: load_interface
SubTest: set_mode
changing mode IF -> BL
SubTest: wait_for_remount
unmount took 1.34815120697 s
mount took 5.14588117599 s
Expected remount count of 1 got 0
Board in wrong mode: interface
Traceback (most recent call last):
  File "../test/run_test.py", line 701, in <module>
    main()
  File "../test/run_test.py", line 679, in main
    tester.run_tests()
  File "../test/run_test.py", line 228, in run_tests
    board.load_interface(if_path, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 413, in load_interface
    self.set_mode(self.MODE_BL, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 318, in set_mode
    raise Exception("Could not change board mode")
Exception: Could not change board mode
```

This kind of problem can be detected by checking UMS file `NEED_BL.TXT`:
```
A bootloader update was started but unable to complete.
Reload the bootloader to fix this error message.
```

**Comment by cederom** [comment]
Breaking continous tests caused this issue again:
```
Board: Name=Microbit Unique ID=9900000031324e4500599019000000620000000097969901
Application: Name=kl26z_microbit_if
Bootloader: Name=kl26z_bl
Target: Name=Microbit
SubTest: load_interface
SubTest: set_mode
changing mode IF -> BL
SubTest: wait_for_remount
unmount took 0.925055980682 s
mount took 4.19406199455 s
Expected remount count of 1 got 0
Board in wrong mode: interface
Traceback (most recent call last):
  File "../test/run_test.py", line 701, in <module>
    main()
  File "../test/run_test.py", line 679, in main
    tester.run_tests()
  File "../test/run_test.py", line 228, in run_tests
    board.load_interface(if_path, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 413, in load_interface
    self.set_mode(self.MODE_BL, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 318, in set_mode
    raise Exception("Could not change board mode")
Exception: Could not change board mode

(venv-mac-27) iCeDeROM:tools cederom$ mbedls
+----------------+----------------------+-------------------+------------------------+--------------------------------------------------+-----------------+
| platform_name  | platform_name_unique | mount_point       | serial_port            | target_id                                        | daplink_version |
+----------------+----------------------+-------------------+------------------------+--------------------------------------------------+-----------------+
| K64F           | K64F[0]              | /Volumes/DAPLINK  | /dev/tty.usbmodem14132 | 0240000028884e45001070116bf000478021000097969900 | 0243            |
| NRF51_MICROBIT | NRF51_MICROBIT[0]    | /Volumes/MICROBIT | /dev/tty.usbmodem14142 | 9900000031324e4500599019000000620000000097969901 | 0243            |
+----------------+----------------------+-------------------+------------------------+--------------------------------------------------+-----------------+

(venv-mac-27) iCeDeROM:tools cederom$ ls /Volumes/MICROBIT/
DETAILS.TXT	MICROBIT.HTM	NEED_BL.TXT
```

**Comment by cederom** [comment]
Fix is proposed at https://github.com/mbedmicro/DAPLink/pull/307

**Comment by cederom** [comment]
https://github.com/mbedmicro/DAPLink/pull/307 fix accepted and merged to upstream, closing issue. Just remember to use `--loadbl` flag in order to get bootloader restored:

```
$ python run_test.py --targetdir ../bin/target/
SubTest: Build test configuration
Test configurations to be run:
    0: APP=kl26z_microbit_if BL=kl26z_bl Board=Microbit Target=Microbit

Fimrware that will not be tested:
    k20dx_frdmk64f_if
    sam3u2c_mkit_dk_dongle_nrf5x_if

Board: Name=Microbit Unique ID=9900000031324e4500599019000000620000000097969901
Application: Name=kl26z_microbit_if
Bootloader: Name=kl26z_bl
Target: Name=Microbit
SubTest: load_interface
SubTest: set_mode
changing mode IF -> BL
SubTest: wait_for_remount
unmount took 1.45076704025 s
mount took 4.83918309212 s
Expected remount count of 4 got 0
Board in wrong mode: interface
Traceback (most recent call last):
  File "run_test.py", line 701, in <module>
    main()
  File "run_test.py", line 679, in main
    tester.run_tests()
  File "run_test.py", line 233, in run_tests
    board.load_interface(if_path, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 416, in load_interface
    self.set_mode(self.MODE_BL, test_info)
  File "/(...)/DAPLink.git/test/daplink_board.py", line 318, in set_mode
    raise Exception("Could not change board mode")
Exception: Could not change board mode

$ python run_test.py --targetdir ../bin/target/ --loadbl
SubTest: Build test configuration
Test configurations to be run:
    0: APP=kl26z_microbit_if BL=kl26z_bl Board=Microbit Target=Microbit

Fimrware that will not be tested:
    k20dx_frdmk64f_if
    sam3u2c_mkit_dk_dongle_nrf5x_if

Board: Name=Microbit Unique ID=9900000031324e4500599019000000620000000097969901
Application: Name=kl26z_microbit_if
Bootloader: Name=kl26z_bl
Target: Name=Microbit
SubTest: load_bootloader
SubTest: set_mode
programming took 0.000237941741943 s
SubTest: wait_for_remount
unmount took 3.444024086 s
mount took 4.53079891205 s
SubTest: set_mode
Bootloader crc: 0x29ec220c
SubTest: load_interface
SubTest: set_mode
changing mode IF -> BL
SubTest: wait_for_remount
unmount took 0.727248907089 s
mount took 5.06676292419 s
programming took 0.000413179397583 s
SubTest: wait_for_remount
unmount took 5.8506360054 s
```
